plugins {
    id "org.jetbrains.intellij.platform" version "2.10.5"
}

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    compileOnly project(":record-builder")

    intellijPlatform {
        intellijIdea("2025.2.5")
        bundledPlugin("com.intellij.java")
    }
}

intellijPlatform {
    pluginConfiguration {
        ideaVersion {
            sinceBuild = "252"
        }
    }
}
