package recordbuilder;

/**
 *
 *
 * @author Freeman
 */
class Over64FieldsTest {
    @RecordBuilder
    record Over64Fields(
            int field1,
            int field2,
            int field3,
            int field4,
            int field5,
            int field6,
            int field7,
            int field8,
            int field9,
            int field10,
            int field11,
            int field12,
            int field13,
            int field14,
            int field15,
            int field16,
            int field17,
            int field18,
            int field19,
            int field20,
            int field21,
            int field22,
            int field23,
            int field24,
            int field25,
            int field26,
            int field27,
            int field28,
            int field29,
            int field30,
            int field31,
            int field32,
            int field33,
            int field34,
            int field35,
            int field36,
            int field37,
            int field38,
            int field39,
            int field40,
            int field41,
            int field42,
            int field43,
            int field44,
            int field45,
            int field46,
            int field47,
            int field48,
            int field49,
            int field50,
            int field51,
            int field52,
            int field53,
            int field54,
            int field55,
            int field56,
            int field57,
            int field58,
            int field59,
            int field60,
            int field61,
            int field62,
            int field63,
            int field64,
            int field65) {}
}
